---

- name: add docker apt key
  become: yes
  get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "/etc/apt/trusted.gpg.d/docker.asc"
    mode: "0644"

- name: add docker apt repo
  become: yes
  apt_repository: repo="deb [arch=arm64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu noble stable"

- name: install docker apt packages
  become: yes
  apt: name="docker-ce"

- name: add korsync user
  become: yes
  user: name="korsync" shell="/bin/false" system="yes" create_home="yes" groups="docker"

- name: make korsync dir
  become: yes
  file:
    path: "{{item}}"
    state: "directory"
    owner: "korsync"
    group: "korsync"
    mode: "0755"
  loop:
    - "{{korsync_dir}}"
    - "{{korsync_dir}}/data/redis"

- name: configure korsync docker compose
  become: yes
  template:
    src: "docker-compose.yml.j2"
    dest: "{{korsync_dir}}/docker-compose.yml"
    owner: "korsync"
    group: "korsync"
    mode: "0600"

- name: ensure docker is started
  become: yes
  systemd: name="docker.service" enabled="yes" state="started"

- name: docker compose pull
  become: yes
  become_user: "korsync"
  command: "docker compose pull"
  args:
    chdir: "{{korsync_dir}}"
  changed_when: false

- name: docker compose
  become: yes
  become_user: "korsync"
  command: "docker compose up -d"
  args:
    chdir: "{{korsync_dir}}"
  changed_when: false
