---

- name: check if pleroma version already installed
  stat:
    path: "/opt/pleroma/releases/{{pleroma_version}}"
  register: installed_version

- name: download and unarchive pleroma release
  become: yes
  unarchive:
    src: "{{pleroma_download_url}}"
    dest: "/tmp/"
    remote_src: yes
  when: not installed_version.stat.exists

- name: delete old pleroma release
  become: yes
  file:
    path: "/opt/pleroma/"
    state: "absent"
  when: not installed_version.stat.exists

- name: install pleroma release
  become: yes
  copy:
    remote_src: true
    src: "/tmp/release/"
    dest: "/opt/pleroma/"
  when: not installed_version.stat.exists
  notify: restart all pleroma instances
